name: Build Docker Image

on:
  push:
    branches:
      - main
    paths: 
      - KmLog.Server/**
      - .github/workflows/docker-action.yml

jobs:
  build-package:
    name: Build and Publish Github Package via Dockerfile
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: kmlogserver
          dockerfile: KmLog.Server/KmLog.Server.WebApi/Dockerfile
          build-context: KmLog.Server
