name: Server CI

on: 
  push:
    paths: 
      - KmLog.Server/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      shell: bash
      run: |
        pushd ./KmLog.Server
        dotnet build -c Release
        popd
