name: Server CI

on: 
  push:
    branches:
      - main
    paths:
      - KmLog.Server/**
      - .github/workflows/server-action.yml
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1 # use dotnet version from global.json
    - name: Build with dotnet
      working-directory: KmLog.Server
      shell: bash
      run: dotnet build -c Release