name: Server CI

on: 
  push:
    paths: 
      - KmLog.Server/**
      - .github/workflows/server-action.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Build with dotnet
      working-directory: KmLog.Server
      shell: bash
      run: dotnet build -c Release

  build-package:
    if: success()
    name: Build and Publish Github Package via Dockerfile
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          working-directory: KmLog.Server
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: kmlogserver
          dockerfile: KmLog.Server.WebApi/Dockerfile
